# Generated by Django 4.2.2 on 2025-02-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Роль"
            ),
        ),
    ]
