# Generated by Django 4.2.2 on 2025-02-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default=2, max_length=300, verbose_name="Роль"),
            preserve_default=False,
        ),
    ]
