# Generated by Django 4.2.2 on 2025-02-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_date_of_birth_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
