# Generated by Django 4.2.2 on 2024-11-04 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_of_question",
                    models.TextField(
                        help_text="Введите вопро ", unique=True, verbose_name="Вопрос"
                    ),
                ),
                (
                    "question_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество баллов"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_of_test",
                    models.CharField(
                        help_text="Название теста",
                        max_length=300,
                        unique=True,
                        verbose_name="Название теста",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.CreateModel(
            name="UserTestAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество попыток"
                    ),
                ),
                (
                    "attempt_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Попытка"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В процессе"),
                            ("passed", "Пройден"),
                            ("failed", "Не пройден"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "users_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tests",
                        to="study.tests",
                        verbose_name="Тест",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextAnswerForQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.TextField(help_text="Ваш ответ", verbose_name="Ответ"),
                ),
                (
                    "right_answer",
                    models.BooleanField(default=False, verbose_name="Правильный ответ"),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="Балл")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_answers",
                        to="study.questions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на вопрос",
                "verbose_name_plural": "Ответы на вопросы",
            },
        ),
        migrations.AddField(
            model_name="questions",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="study.tests",
            ),
        ),
        migrations.CreateModel(
            name="ChoicesForQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_of_choice",
                    models.TextField(
                        help_text="Введите вариант ответа",
                        unique=True,
                        verbose_name="Вариант ответа",
                    ),
                ),
                (
                    "right_answer",
                    models.BooleanField(default=False, verbose_name="Правильный ответ"),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="Балл")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="study.questions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
            },
        ),
    ]
