# Generated by Django 4.2.2 on 2024-11-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tests",
            name="questions_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество вопросов"
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="total_score",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Общее количество очков"
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="name_of_question",
            field=models.TextField(
                help_text="Введите вопрос", unique=True, verbose_name="Вопрос"
            ),
        ),
    ]
