# Generated by Django 4.2.2 on 2024-11-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_tests_questions_count_tests_total_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questions",
            name="question_score",
        ),
    ]
