# Generated by Django 4.2.2 on 2024-12-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_remove_questions_question_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choicesforquestions",
            name="name_of_choice",
            field=models.TextField(
                help_text="Введите вариант ответа", verbose_name="Вариант ответа"
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="name_of_question",
            field=models.TextField(help_text="Введите вопрос", verbose_name="Вопрос"),
        ),
    ]
