# Generated by Django 4.2.2 on 2024-12-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_alter_choicesforquestions_name_of_choice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertestassignment",
            name="users_test",
        ),
        migrations.AddField(
            model_name="usertestassignment",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tests",
                to="study.tests",
                verbose_name="Тест",
            ),
        ),
    ]
